fix(config): bat cannot print file paths that starts with '-' on windows (#946)
## 📺 PR Description

<!-- summary of the change + which issue is fixed if applicable. -->
when trying to print content of file paths that starts with '-' on
windows, bat puts out this error:
error: unexpected argument '-1' found

  tip: to pass '-1' as a value, use '-- -1'

Usage: bat.exe [OPTIONS] [FILE]...
       bat.exe <COMMAND>

For more information, try '--help'.

<!-- a quick pass through the following items to make sure you haven't
forgotten anything -->

- [x] my commits **and PR title** follow the [conventional
commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
- [x] if this is a new feature, I have added tests to consolidate the
feature and prevent regressions
- [ ] if this is a bug fix, I have added a test that reproduces the bug
(if applicable)
- [x] I have added a reasonable amount of documentation to the code
where appropriate